development:
  address: "stmp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "wallmth2018@gmail.com"
  password: "wall2018"
  enable_starttls_auto: true

production:
  address: "smtp.mailgun.org"
  port: 587
  domain: "mg.wallindie.com"
  authentication: "plain"
  user_name: "postmaster@mg.wallindie.com"
  password: "cca71586a486c355462ae44f09c8f285-21e977f8-c0ed5df1"
  enable_starttls_auto: true
